# Generated by Django 4.1.2 on 2022-12-19 06:31

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Имя')),
                ('descriptions', models.TextField(blank=True, verbose_name='описание')),
                ('photo_file', models.ImageField(blank=True, max_length=254, null=True, upload_to=main.models.get_timestamp_path)),
            ],
        ),
    ]
